specfile_path: arm-image-installer.spec
downstream_package_name: arm-image-installer
upstream_project_url: https://github.com/fedora-arm/arm-image-installer

upstream_tag_template: v{version}

files_to_sync:
  - src:
      - "arm-image-installer.spec"
      - ".packit.yaml"
    dest: .

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-stable
      - fedora-development
    tf_extra_params:
      environments:
        - arch: aarch64

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-stable
      - fedora-development

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-latest-stable
      - fedora-development

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-latest-stable
      - fedora-development

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-latest-stable
      - fedora-development
